jQuery().ready( function(){
	new com_paulacska();
});

/**
  *	Paula's homepage
  *	Written quickly!
  *
  * @author Lee
  *
  * @classdesc
  *	Usage:
  *
  *	.close - clicking elements of this class will hide the parent element
  *
  *	.portfolio - clicking elements of this class will display a portfolio of
  *		images linked from the HTML page (generated by Apache `mod_autoindex`)
  *		specified in the `data-uri` attribute, provided the links match
  *		 /_thumb/ and do not contain slashses. Full-sized images are expected
  *		 to have the same filename, without the `_thumb` string. Change the
  *		 regex by supplying the option `thumbRegex`.
  *
  *	#slideshow - if present, will produce a full-screen slideshow,
  *		from all images linked on the HTML page (`mod_autoindex`-like)
  *		linked from the `data-uri` attribute, with a dealy between
  *		slides of the number of MS specified in the attribute `data-intervalms`.
  *
  * @constructor
  * @param {object} options
  */
function com_paulacska( options ){
	var self = this;
	this.options = options || {};
	// Only one of click2open div open at a time:
	this.click2openCurrentContainer = null;

	this.slideshow = new com_paulacska_slideshow({
		uri:		jQuery('#slideshow').attr('data-uri'),
		element:	jQuery('#slideshow'),
		intervalms: parseInt(jQuery('#slideshow').attr('data-intervalms'), 10) || 3000
	});

/*
	// Load fonts:
	var fonts = [
	//	['Rock+Salt::latin', 'Special+Elite::latin'],
		['Roboto:400,100:latin', 'Roboto::latin']
	];
	var fontsToUse = fonts[ Math.floor((Math.random()*fonts.length)) ];
 	WebFontConfig = {
    	google: { families: fontsToUse }
  	};
  	if (console) console.log( fontsToUse );
    var wf = document.createElement('script');
    wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
      '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
    wf.type = 'text/javascript';
    wf.async = 'true';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(wf, s);

    // Apply fonts on body and h1-6
    var headerFontName 	= decodeURI( fontsToUse[0] );
    headerFontName 		= headerFontName.replace( /:.+$/, '' );
    headerFontName 		= headerFontName.replace( /\+/g, ' ' );
    var bodyFontName	= decodeURI( fontsToUse[1] );
    bodyFontName 		= bodyFontName.replace( /:.+$/, '' );
    bodyFontName 		= bodyFontName.replace( /\+/g, ' ' );
    jQuery( "<style>"
    	+ "h1,h2,h3,h4,h5,h6 { font-family:'"+headerFontName+"'}"
    	+ "body {font-family:'"+bodyFontName+"'}"
    	+ "</style>"
    ).appendTo( "head");
*/

	// Vertically centre the menu - ugh:
	var nav = jQuery('#top-level-navigation');
	nav.css({
		'margin-top': (jQuery(window).height() - nav.height() ) /2
	});

	jQuery('.close').on('click', function(e){
		location.hash = '';
		jQuery(e.target.parentElement).animate({
			opacity: 0
		}, 500, function(){
			jQuery(e.target.parentElement).hide();
		});
		self.click2openCurrentContainer = null;
	});

	jQuery('.click2open').on('click', function(e){
		e.stopPropagation();
		self.headerOrigOpacity = $('header').css('opacity');
		$('header').css('opacity', .2)
		if (self.click2openCurrentContainer != null){
			var c = self.click2openCurrentContainer;
			self.click2openCurrentContainer.animate({
				opacity: 0
			}, 300, function(){
				c.hide();
			});
		}
		var id = jQuery(this).attr('data-uri');
		location.hash = 'click2open/'+id;
		var container = jQuery('#'+ id );
		self.click2openCurrentContainer = container;

		// The the element named on the caller's data-uri attribute
		jQuery(document.body).on('click',function(e){
			jQuery(document.body).off();
			$('header').css('opacity', self.headerOrigOpacity)
			var c = self.click2openCurrentContainer;
			self.click2openCurrentContainer.animate({
				opacity: 0
			},200, function(){
				c.hide();
				window.scrollTo(0,0);
				location.hash = '';
				self.click2openCurrentContainer = null;
			});
			if (! jQuery(e.target).attr('href')){
				e.preventDefault();
			}
		});
		container.removeClass('initially-hidden');
		container.addClass('clicked2open');
		container.show();
		var top =  (jQuery(window).height()/2) - ((100+container.height())	/2);
		if (top < 0){
			top = 10;
		}
		container.animate({
			opacity: 0.95,
			left: (jQuery(document.body).width()/2) - (container.width()/2),
			top: top
		}, 1000);
	});

	jQuery('.portfolio').each( function(i,j){
		self.addPortfolio(j)
	});

	// Hack hash
	if (window.location.hash){
		var hash = window.location.hash.substr(1);
		if (hash){
			// URI == the class/data-uri attributes of an element
 			var uriParts = decodeURI(hash).split('/');
			var el = $('.'+uriParts[0]+'[data-uri="'+uriParts[1]+'"]');
			if (console) console.log( el, uriParts)
			if (el.length){
//				self.slideshow.stop();
 				el.trigger('click');
				if (uriParts[1]){
					var path = decodeURI(hash);
					var ext  = path.match('(png|jpg)$');
					if (ext){
						var re = new RegExp( '\.' + ext[1] + '$' );
						var thumbPath = path.replace( re, '_thumb.'+ext[1] );
						var tryInterval; // Takes a while to load and we've 'loaded' event yet
						tryInterval = setInterval(
							function(){
								var imgEl = jQuery("img[src='" + thumbPath +"']");
								if (imgEl){
									clearInterval( tryInterval );
									imgEl.trigger('click');
								}
							},
							1000
						);
					}
				}
			}

			// URI does not reflect an element, but is perhaps a portfolio URI
			else {
				if (uriParts[0] === 'portfolio')
					self.addPortfolio( uriParts[1])
			}
		}
	}
}

/*
	Add a portfolio by element or directory name.
	For the former case, pass the name of the element.
*/
com_paulacska.prototype.addPortfolio = function( j ){
	var self = this;
	var el;
	var args = {
		slideshow: false,
		intervalms:	5000,
		onClose: function(){
			self.slideshow.start();
		},
	};
	if (self.options.thumbRegex){
		args.thumbRegex = self.options.thumbRegex;
	}

	if (typeof j == 'string') {
		args.uri = j;
		args.title = j.replace(/[_\W]+/g, ' ');
	}
	else {
		el = jQuery(j);
		args.uri = el.attr('data-uri');
		if (el.attr('data-title')) args.title = el.attr('data-title');
		if (el.attr('data-thumbregex')) args.thumbRegex = el.attr('data-thumbregex');
		if (el.attr('data-noslideshow')){
			args.slideshow = false;
		} else {
			args.slideshow = true;
		}
	}

	var portfolio = new com_paulacska_portfolio(args);

	// Make the passed link clickable
	if (el){
		el.on('click', function(){
			self.slideshow.stop();
			portfolio.show();
		});
	}

	// The show passed portfolio
	else {
		console.info("Showing portfolio from URI, "+j)
		self.slideshow.stop();
		portfolio.show();
	}
}

/*
	@param options.uri - uri of `mod_autoindex` directory or similar HTML page
	@param options.onComplete - callback
*/
function com_paulacska_imagesFromIndex( options ) {
	var self = this;
	this.options = options;
	if (!this.options.uri){
		throw 'No uri?';
	}

	this.images = [];

	$.get( this.options.uri, function(rv) {
		var html = jQuery('<html/>', { html: rv });
		html.find('a').each( function(i,el){
			// Only links to images
			if (jQuery(el).attr('href').match(/(png|jpe?g|gif)$/i)){
				self.images.push( self.options.uri +'/'+ jQuery(el).attr('href') );
			}
		});
		if (self.options.onComplete){
			self.options.onComplete.call();
		}
	});
}

com_paulacska_resizer = function(){}
com_paulacska_resizer.prototype.resize = function(img){
	// Can't rely upon CSS3 'contain'
	// Plus note the size may change, so get this every time:
	var contWidth	= jQuery(window).width();
	var contHeight	= jQuery(window).height();
	var maxx		= contWidth;
	var maxy  		= contHeight;
	// Sometimes we get a jQuery object, which nastily over-writes an attribute with a function:
	var imgWidth	= typeof img.width=='function'? img.width() : img.width;
	var imgHeight	= typeof img.height=='function'? img.height() : img.height;
	var r = (imgWidth/maxx) > (imgHeight/maxy)
		? (imgWidth/maxx)
		: (imgHeight/maxy);

	if (r<1) {
		 r = 1
	}
	if (console) console.info(imgWidth+' v '+contWidth, ', ', imgHeight+' v '+contHeight	, r);
	img.width  = imgWidth / r;	// Changes the height too!
	img.height = imgHeight / r;
	if (console) console.info(img.width, img.height);

	jQuery(img).css({
		'position': 'absolute',
		'opacity':	0,
		'z-index':	99,
		'width': 	img.width,
		'height': 	img.height,
		'left':  	(contWidth/2)  - (img.width  /2),
		'top':  	(contHeight/2) - (img.height /2)
	});

	return img;
}


// Load image list:
// @param options.uri String, uri to .json file or directory of images or htm page of a links
// If dir or HTML page, greps links without oblique in their href.
com_paulacska_slideshow = function( options ){
	var self = this;
	this.options = options;
	if (!this.options.element){
		throw'No element?';
	}
	if (!this.options.uri){
		throw'No uri?';
	}

	this.resizer = new com_paulacska_resizer();

	this.options.element.css({
	    'position': 'absolute',
		'display': 'block',
		'overflow': 'hidden',
		'width': '100%',
		'height': '100%',
		'top': 0,
		'left': 0
	});

	if (this.options.uri.match(/json$/)){
		jQuery.getJSON( this.options.uri, function(json) {
			self.imagesFromIndex = {};
			self.imagesFromIndex.images = json.images;
			self._create();
		});
	}

	else {
		this.imagesFromIndex = new com_paulacska_imagesFromIndex({
			uri: this.options.uri,
			onComplete: function(){
				self._create();
			}
		});
	}
};

/* Create slideshow in this.options.element from images in this.images that
	match this.options.thumbRegex */
com_paulacska_slideshow.prototype._create = function(){
	// First call:
	if (this.index == null){
		this._displayImage();
	}
	this.start();
};

com_paulacska_slideshow.prototype.start = function(){
	var self = this;
	if (this.interval) clearInterval(this.interval);
	this.interval = setInterval(function() {
		self._displayImage();
	}, self.options.intervalms);
};

com_paulacska_slideshow.prototype.stop = function(){
	clearInterval(this.interval);
	this.interval = null;
};

com_paulacska_slideshow.prototype._displayImage = function(){
	var self = this;
	if (this.index == null){
		this.index = -1;
	}
	this.index ++;
	if (this.index == this.imagesFromIndex.images.length){
		this.index = 0;
	}

	// When the image loads, scale it, fade it in, and remove any previous image
	var img = new Image();

	jQuery(img).load( function(){
		self.options.element.append(img);

		img = self.resizer.resize(img);

		jQuery(img).animate(
			{ opacity:1 },
			666,
			function(){ // Messy because of IE e.target being unreliable
				var oldImg = self.options.element.children();
				if (oldImg.length>1){
					jQuery(oldImg[0]).animate(
						{ opacity:0 },
						666,
						function(){
							jQuery(img).css('z-index', 100);
							jQuery(oldImg[0]).remove();
						}
					);
				}
			}
		);
	}); // End img.onload
	img.src = encodeURI(this.imagesFromIndex.images[ this.index ]);
};



/*
	@param options.thumbRegex : Regular expression to identify thumbnails
	@param options.uri : HTML from which to extract links (mod_autoindex)
		Every image linked should have a thumbnail with same name and suffix  `_thumb` before the ext.
*/
function com_paulacska_portfolio( options ) {
	var self = this;
	this.options = options;
	if (!this.options.uri){
		throw 'No portfolio uri?';
	}

	this.options.slideshow	= this.options.slideshow || false;
	this.options.intervalms	= this.options.intervalms || 4000;
	this.options.thumbRegex = this.options.thumbRegex || /_thumb/ig;

	if ( typeof this.options.thumbRegex != 'object'){
		this.options.thumbRegex = new RegExp( this.options.thumbRegex, 'ig');
	}

	this.interval			= null;
	this.cache 				= [];	// All images
	this.bigImageIndex		= null;	// Currently showing
	this._oldBigImageIndex	= null;
	this.hash				= 'portfolio/'+this.options.uri;

	this.resizer  = new com_paulacska_resizer();

	// Mask
	this.portfolioEl = jQuery('<div/>', {
	//	'title': 'Click here to go back',
		'class': 'mask portfolio-container'
	});
	this.portfolioEl.appendTo(document.body);
	this.portfolioEl.hide();
	// Cancel by clicking the mask
	// this.portfolioEl.on('click', function(e){
	//	self.hide();
	// });

	// Close button
	this.closeEl = jQuery('<div/>', {
		'title': 'Click here to go close this portfolio',
		'class': 'close-big top'
	});
	this.closeEl.appendTo( this.portfolioEl );
	this.closeEl.on('click', function(e){
		self.hide();
		self.options.onClose.call();
	});

	this.portfolioMaskEl = jQuery('<div/>', {
	//	'title': 'Click here to go back',
		'class': 'mask',
		'id': 'portfolio-bigimg-mask'
	});
	this.portfolioMaskEl.appendTo(document.body);
	this.portfolioMaskEl.hide();

	this.imagesFromIndex = new com_paulacska_imagesFromIndex({
		uri: this.options.uri,
		onComplete: function(){
			self._create();
		}
	});
}

com_paulacska_portfolio.prototype._create = function(){
	var self = this;
	var j = -1;

	if (this.options.title){
		jQuery('<h2/>', { html: this.options.title }).
			prependTo(self.portfolioEl);
	}

	jQuery.each( this.imagesFromIndex.images, function(idx,i){

		// For each thumbnail, create a clickable image
		if (i.match( self.options.thumbRegex )){
			j++;

			self.cache[j] = {};
			self.cache[j].src = i.replace( self.options.thumbRegex, '');
			var title = self.cache[j].src.match(/([^\/]+)\.\w+$/)[1].toLowerCase().replace(/[_-]+/gi, ' ');

			self.cache[j].img = new Image();
			self.cache[j].img.src = i;
			self.cache[j].bigImg = jQuery('<img/>', {
			// src: self.cache[j].src });
				alt: title,
				title: title
			});

			self.cache[j].bigImg.appendTo( self.portfolioMaskEl );
			self.cache[j].bigImg.hide();

			var thumbImage = jQuery('<img/>', {
				// 'class':	'thumb',
				'src':		i,
				'data-index': j,
				'alt':		title,
				'title':	title
			});
			thumbImage.on('click', function(e){
				// Why is 'j' not frozen by closure?
				self.showBigImage( jQuery(e.target).attr('data-index') );
				e.preventDefault();
				return false;
			});
			thumbImage.appendTo( self.portfolioEl );
		}
	});
};

com_paulacska_portfolio.prototype.show = function(){
	location.hash = this.hash;
	var self = this;
	this.portfolioEl.show();
	// Cancel with back,esc
	jQuery(window).on("navigate", function (e, data) {
		if (data.state.direction == 'back') {
			e.preventDefault();
			self.hide();
		}
	});
	jQuery(document.body).off('keyup');
	jQuery(document.body).on('keyup', function(e){
		console.log('key ', e.keyCode, self.bigImageIndex);
		if (e.keyCode == 8 || e.keyCode == 224 || e.keyCode == 27){
			e.preventDefault();
			if (self.bigImageIndex !== null) self.closeBigImage();
			self.hide();
		}
		else if ( e.keyCode == 39 || e.keyCode == 32){
			e.preventDefault();
			if (self.bigImageIndex !== null) self.nextBigImg();
		} else if (e.keyCode == 37) {
			e.preventDefault();
			if (self.bigImageIndex !== null) self.previousBigImg();
		}
	});
};

com_paulacska_portfolio.prototype.hide = function(){
	location.hash = '';
	this.portfolioEl.hide();
	jQuery(window).off("navigate");
	jQuery(document.body).off('keyup');
};

com_paulacska_portfolio.prototype.closeBigImage = function(){
	location.hash = this.hash;
	this.hideBigImgNav();
	jQuery(document.body).off('keyup');
	jQuery(document.body).off('click');
	jQuery(document.body).off('mousemove');
	this.cache[ this.bigImageIndex ].bigImg.hide();
	this.portfolioMaskEl.hide();
	if (this.interval != null){
		clearInterval(this.interval);
	}
	jQuery(document.body).css({
		height: 'auto',
		overflow: 'auto'
	});
};

com_paulacska_portfolio.prototype.showBigImage = function(index){
	var self = this;

	if (index == null) {
		throw new Error('showBigImage now requires in index to set bigImageIndex');
	}

	// Prevent request for next image when we're loading it
	this.hideBigImgNav();

	// Get rid of any current image
	if (this._oldBigImageIndex){
		var dir = this._oldBigImageIndex > this.bigImageIndex? 1 : -1;
		// animImg.addClass('spin');
		self.cache[ this.bigImageIndex ].bigImg.animate(
			{
				opacity: 0,
				left: jQuery(window).width() * dir
			},
			666,
			function(){
				// animImg.removeClass('spin');
				// animImg.hide();
			}
		);
	}

	if (this.bigImageIndex != null) {
		this._oldBigImageIndex = this.bigImageIndex;
	}

	this.bigImageIndex = index;

	// Allow incoming links and history.back
	location.hash = self.cache[ this.bigImageIndex ].src;

	// Stop all scrolling:
	jQuery(document.body).css({
		height: jQuery(window).height(),
		overflow: 'hidden'
	});
	// Just in case caller did not show this:
	this.portfolioMaskEl.show();
	this.portfolioMaskEl.css({
		top: jQuery(document).scrollTop()
	});

	if (typeof self.cache[ this.bigImageIndex ].bigImg.attr('src') == 'undefined'){
		this.portfolioMaskEl.css('cursor', 'wait');
		self.cache[ this.bigImageIndex ].bigImg.attr('src', self.cache[ this.bigImageIndex ].src);
		self.cache[ this.bigImageIndex ].bigImg.on('load', function(){
			self.portfolioMaskEl.css('cursor', 'default');
			self.loadedBigImage();
		});
	} else {
		self.loadedBigImage();
	}
};

com_paulacska_portfolio.prototype.loadedBigImage = function(index){
	var self = this;

	jQuery(document.body).off('click');
	// jQuery(document.body).off('keyup');
	// jQuery(document.body).on('keyup', function(e){
	// 	if (e.keyCode == 8 || e.keyCode == 224 || e.keyCode == 27){
	// 		e.preventDefault();
	// 		self.closeBigImage();
	// 	}
	// });

	this.cache[this.bigImageIndex].bigImg = self.resizer.resize(
		this.cache[this.bigImageIndex].bigImg
	);

	this.cache[this.bigImageIndex].bigImg.show();

	var ready = function(){
		self._oldBigImageIndex = self.bigImageIndex;

		self.cache[self.bigImageIndex].bigImg.css({
			'opacity':	1,
			'left': (jQuery(document).width() /2) - (self.cache[self.bigImageIndex].bigImg.width  / 2)
		});

		/* Close the image on a click
		jQuery(document.body).on('click', function(e){
			e.preventDefault();
			self.closeBigImage();
			return false;
		});
		*/

		// Cue the next image:
		if (self.options.slideshow){
			clearTimeout(self.interval);
			self.interval = setTimeout(function() {
				self.nextBigImg();
			}, self.options.intervalms);
		}

		// No slideshow
		else {
			self.showBigImgNav();
		}
	}; // End 'ready'

	// A previous image to clear prior to calling 'ready'?
	if (self._oldBigImageIndex == null){
		ready.call();
	}

	else {
		this.cache[this.bigImageIndex].bigImg.animate({
				opacity: 1
			},
			666,
			function(){
				ready.call();
			}
		);
	}
};


com_paulacska_portfolio.prototype.showBigImgNav = function(){
	// Initiate navigation if necessary
	if ( jQuery('#bigImgNavLeft').length === 0 ){
		var self = this;
		var h = jQuery(window).height();
		var l = jQuery('<div/>', { id: 'bigImgNavLeft', text:'<', title:'Previous Image' });

		// Previous image
		l.css('top', (h/2) - (l.height()/2));
		l.on('click', function(e){
			e.preventDefault();
			e.stopPropagation();
			self.previousBigImg();
		});
		jQuery( this.portfolioMaskEl ).append(l);

		// Next image
		var r = jQuery('<div/>', { id: 'bigImgNavRight', text:'>', title:'Next Image' });
		r.css('top', (h/2) - (r.height()/2));
		r.on('click', function(e){
			e.preventDefault();
			e.stopPropagation();
			self.nextBigImg();
		});
		jQuery( this.portfolioMaskEl ).append(r);

		// Close button
		this.closeEl = jQuery('<div/>', {
			'title': 'Click here to go close this image',
			'class': 'close-big',
			'id':  	 'bigImgNavClose'
		});
		this.closeEl.appendTo( this.portfolioMaskEl );
		this.closeEl.on('click', function(e){
			e.preventDefault();
			self.closeBigImage();
		});
	}

	// Show already-created navigation:
	else {
		this.closeEl.show();
		jQuery('#bigImgNavLeft').show();
		jQuery('#bigImgNavRight').show();
	}
};

com_paulacska_portfolio.prototype.hideBigImgNav = function(){
	if ( jQuery('#bigImgNavLeft').length > 0 ){
		this.closeEl.hide();
		jQuery('#bigImgNavLeft').hide();
		jQuery('#bigImgNavRight').hide();
	}
};

com_paulacska_portfolio.prototype.nextBigImg = function(){
	var nextIndex = parseInt(this.bigImageIndex, 10) +1;
	if (nextIndex >= this.cache.length){
		nextIndex = 0;
	}
	this.showBigImage( nextIndex );
};

com_paulacska_portfolio.prototype.previousBigImg = function(){
	var nextIndex = parseInt(this.bigImageIndex, 10) -1;
	if (nextIndex < 0 ){
		nextIndex = this.cache.length -1;
	}
	this.showBigImage(nextIndex);
};
